name: Deploy Blue-Green to Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/lugx_Gaming-CW
            git pull

            echo "Deploying BLUE versions..."
            kubectl apply -f k8s/blue-green/game-service-blue.yaml
            kubectl apply -f k8s/blue-green/order-service-blue.yaml
            kubectl apply -f k8s/blue-green/analytics-service-blue.yaml

            echo "Checking readiness..."
            kubectl rollout status deployment/game-service-blue --timeout=60s
            kubectl rollout status deployment/order-service-blue --timeout=60s
            kubectl rollout status deployment/analytics-service-blue --timeout=60s

            echo "Switching Services to BLUE..."
            kubectl patch service game-service -p '{"spec":{"selector":{"app":"game-service","version":"blue"}}}'
            kubectl patch service order-service -p '{"spec":{"selector":{"app":"order-service","version":"blue"}}}'
            kubectl patch service analytics-service -p '{"spec":{"selector":{"app":"analytics-service","version":"blue"}}}'

            echo "Scaling down GREEN..."
            kubectl scale deployment/game-service-green --replicas=0 || true
            kubectl scale deployment/order-service-green --replicas=0 || true
            kubectl scale deployment/analytics-service-green --replicas=0 || true

            echo "Deployment complete."
