name: Deploy to EC2 Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy code and deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.85.29.25 '
          cd lugx_Gaming-CW &&
          git pull origin main &&
          kubectl apply -f lugx-k8s/
        '
